language: cpp

cache:
    - apt
    - ccache

compiler:
    - clang
    - gcc

env:
    - IGNORE_QT=false
    - IGNORE_QT=true
    - SHARED=true
    - SHARED=false

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libqt4-dev libxml++2.6-dev libboost-dev zlib1g-dev
    - mkdir ../build
    - cd ../build

script:
    - "cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_SHARED_LIBS:BOOL=$SHARED -D IGNORE_QT:BOOL=$IGNORE_QT ../CiftiLib"
    - make -j 4
    - ctest
    - sudo make install
