language: cpp
sudo: false

cache:
    - apt
    - ccache

addons:
    apt:
        packages:
            - libqt4-dev
            - libxml++2.6-dev
            - libboost-dev
            - libboost-filesystem-dev
            - zlib1g-dev
            - doxygen

compiler:
    - clang
    - gcc

env:
    matrix:
        - IGNORE_QT=false SHARED=true
        - IGNORE_QT=false SHARED=false
        - IGNORE_QT=true SHARED=true
        - IGNORE_QT=true SHARED=false

before_install:
    - mkdir ../build
    - cd ../build

script:
    - cmake -D BUILD_SHARED_LIBS:BOOL=$SHARED -D IGNORE_QT:BOOL=$IGNORE_QT ../CiftiLib
    - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang-3.9.0/lib'; fi)
    - make -j 4
    - make doc
    - ctest
